[package]
name = "lua-decorator"
version = "0.1.0"
authors = ["Alexey Minchakov <lexaaim@gmail.com>"]
edition = "2018"

[build-dependencies]
# lalrpop = { version = "0.19.0", features = ["lexer"] }
lalrpop = "0.19.0"

[dependencies]
lalrpop-util = "0.19.0"
regex = "1"
